const LOCAL_DNS = "https://zeeven.loca.lt";
const RECETTE_DNS = "https://api.zeeven.chillo.fr";
const PROD_DNS = "https://api.zeeven.fr";
export const ADS_ENDPOINT = "ad";
export const IMAGES_URL = `${LOCAL_DNS}/assets`;
export const BACKEND_URL = `${LOCAL_DNS}`;
export const FAVORITE_ENDPOINT = "favorite";
export const ACCOUNT_ENDPOINT = "account";
export const ADDRESS_ENDPOINT = "address";
