const LOCAL_DNS = 'http://192.168.1.128:8083';
const RECETTE_DNS = "https://api.zeeven.chillo.fr";
const PROD_DNS = "https://api.zeeven.fr";
export const ADS_ENDPOINT = "ad";
export const IMAGES_URL = `${PROD_DNS}/assets`;
export const BACKEND_URL = `${PROD_DNS}`;
export const FAVORITE_ENDPOINT = "favorite";
export const ACCOUNT_ENDPOINT = "account";
export const ADDRESS_ENDPOINT = "address";
